name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: birthday-counter-linux
          - os: windows-latest
            output_name: birthday-counter-windows.exe
          - os: macos-latest
            output_name: birthday-counter-macos
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
    
    - name: Build executable
      run: pyinstaller --onefile main.py -n ${{ matrix.output_name }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.output_name }}
        path: dist/${{ matrix.output_name }}*
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/${{ matrix.output_name }}*
        draft: false
        prerelease: false
        generate_release_notes: true